acme_es_battle_homepage:
    path:     /hello/{name}
    defaults: { _controller: AcmeEsBattleBundle:Default:index }

acme_es_battle_login:
    path:     /login/{username}/{password}
    defaults: { _controller: AcmeEsBattleBundle:Login:index }

acme_es_battle_login_by_token:
    path:     /login/token/{username}/{token}
    defaults: { _controller: AcmeEsBattleBundle:Login:refresh }

acme_es_battle_login_by_forget_token:
    path:     /login/forgetToken/{username}/{token}
    defaults: { _controller: AcmeEsBattleBundle:Login:forgetAuth }

acme_es_battle_login_set_online:
    path:     /login/online/{username}/{token}
    defaults: { _controller: AcmeEsBattleBundle:Login:setOnline }

acme_es_battle_login_refresh_bungie:
    path:     /login/refresh
    defaults: { _controller: AcmeEsBattleBundle:Login:refreshBungie }

acme_es_battle_register:
    path:     /register/{email}/{password}/{username}/{plateformId}/{gamerTag}
    defaults: { _controller: AcmeEsBattleBundle:Login:register }

acme_es_battle_rdv:
    path:     /rdv/.{_format}
    defaults: { _controller: AcmeEsBattleBundle:Rdv:index,_format: json }

acme_es_battle_rdv_create:
    path:     /rdv/add/{plateform}/{game}/{tags}/{description}/{start}/{duree}/{nbParticipant}/{userGameId}/{vignetteId}/{username}/{token}
    defaults: { _controller: AcmeEsBattleBundle:Rdv:create }

acme_es_battle_rdv_get:
    path:     /rdv/get/{rdvId}.{_format}
    defaults: { _controller: AcmeEsBattleBundle:Rdv:getRdvById,_format: json}

acme_es_battle_rdv_join:
    path:     /rdv/join/{rdvId}/{userGameId}/{username}/{apikey}
    defaults: { _controller: AcmeEsBattleBundle:Rdv:joinRdv }

acme_es_battle_rdv_accept_user:
    path:     /rdv/accept_user/{userGameId}/{rdvId}/{username}/{apikey}
    defaults: { _controller: AcmeEsBattleBundle:Rdv:acceptUser }

acme_es_battle_rdv_notification:
    path:     /notifications/{userId}
    defaults: { _controller: AcmeEsBattleBundle:Notification:index }

acme_es_battle_rdv_notification_all:
    path:     /notifications/all/{userId}
    defaults: { _controller: AcmeEsBattleBundle:Notification:getAll }

acme_es_battle_rdv_notification_mark_read:
    path:     /notifications/read/{userId}/{notificationsId}
    defaults: { _controller: AcmeEsBattleBundle:Notification:markAllAsRead }

acme_es_battle_rdv_kick_user:
    path:     /rdv/kick_user/{userGameId}/{rdvId}/{username}/{apikey}
    defaults: { _controller: AcmeEsBattleBundle:Rdv:kickUser }

acme_es_battle_rdv_leave:
    path:     /rdv/leave/{rdvId}/{userGameId}/{username}/{apikey}
    defaults: { _controller: AcmeEsBattleBundle:Rdv:leaveRdv }

acme_es_battle_rdv_promote:
    path:     /rdv/promote/{rdvId}/{userGameId}/{username}/{apikey}
    defaults: { _controller: AcmeEsBattleBundle:Rdv:promoteRdv }

acme_es_battle_rdv_invite:
    path:     /rdv/invite/{userId}/{rdvId}/{username}/{apikey}
    defaults: { _controller: AcmeEsBattleBundle:Rdv:invite }

acme_es_battle_rdv_form_info:
    path:     /rdv/form_info
    defaults: { _controller: AcmeEsBattleBundle:Rdv:getFormInfo }

acme_es_battle_forget_password:
    path:     /forget_password/{email}
    defaults: { _controller: AcmeEsBattleBundle:Login:forgetPassword }

acme_es_battle_update_password:
    path:     /update_password/{password}/{username}/{apikey}
    defaults: { _controller: AcmeEsBattleBundle:Login:updatePassword }

acme_es_battle_game_data_create:
    path:     /game_data/create/{plateformId}/{gameId}/{profilName}/{gameUsername}/{data1}/{data2}/{data3}/{data4}/{username}/{apikey}
    defaults: { _controller: AcmeEsBattleBundle:Login:createUserGame }

acme_es_battle_game_data_update:
    path:     /game_data/update/{plateformId}/{gameId}/{profilId}/{profilName}/{gameUsername}/{data1}/{data2}/{data3}/{data4}/{username}/{apikey}
    defaults: { _controller: AcmeEsBattleBundle:Login:updateUserGame }

acme_es_battle_matchmaking_conf:
    path:     /matchmaking/
    defaults: { _controller: AcmeEsBattleBundle:Matchmaking:index }

acme_es_battle_matchmaking_join:
    path:     /matchmaking/join/{matchmakingId}/{profilId}/{username}/{apikey}
    defaults: { _controller: AcmeEsBattleBundle:Matchmaking:join }

acme_es_battle_users_list:
    path:     /users/
    defaults: { _controller: AcmeEsBattleBundle:User:getUsers }

acme_es_battle_users_list_page:
    path:     /users/page/{page}/{nbResult}
    defaults: { _controller: AcmeEsBattleBundle:User:getUsersByPage }

acme_es_battle_users_list_by_plateform:
    path:     /users/plateform/{plateformId}/{page}/{nbResult}
    defaults: { _controller: AcmeEsBattleBundle:User:getUsersByPlateform }


acme_es_battle_users_search:
    path:     /users/search/{username}/{plateformId}/{page}/{nbResult}
    defaults: { _controller: AcmeEsBattleBundle:User:searchUser }

acme_es_battle_user_get_friend:
    path:     /user/friend/get/{username}/{apikey}
    defaults: { _controller: AcmeEsBattleBundle:User:getFriend }

acme_es_battle_user_get_friend_my_request:
    path:     /user/friend/request/{userId}
    defaults: { _controller: AcmeEsBattleBundle:User:getMyFriendRequest }

acme_es_battle_user_get_friend_request_pending:
    path:     /user/friend/request/pending/{userId}
    defaults: { _controller: AcmeEsBattleBundle:User:getFriendRequest }

acme_es_battle_user_add_friend:
    path:     /user/friend/add/{friendUsername}/{username}/{apikey}
    defaults: { _controller: AcmeEsBattleBundle:User:addFriend }

acme_es_battle_user_remove_friend:
    path:     /user/friend/remove/{friendUsername}/{username}/{apikey}
    defaults: { _controller: AcmeEsBattleBundle:User:removeFriend }

acme_es_battle_user_get_destiny_characters:
    path:     /user/destiny/{membershipType}/{displayName}
    defaults: { _controller: AcmeEsBattleBundle:User:getDestinyUsersGame }

acme_es_battle_bungie:
    path:     /bungie
    defaults: { _controller: AcmeEsBattleBundle:Bungie:index }

acme_es_battle_bungie_characters:
    path:     /bungie/characters/{plateformId}/{plateformBungie}/{gamerTag}/{username}/{apikey}
    defaults: { _controller: AcmeEsBattleBundle:Bungie:getCharacters }

acme_es_battle_bungie_player:
    path:     /bungie/player/{membershipType}/{displayName}
    defaults: { _controller: AcmeEsBattleBundle:Bungie:getPlayer }

acme_es_battle_annonce_create:
    path:     /annonce/create/{tags}/{description}/{userGameId}
    defaults: { _controller: AcmeEsBattleBundle:Annonce:create }

acme_es_battle_annonce:
    path:     /annonce.{_format}
    defaults: { _controller: AcmeEsBattleBundle:Annonce:index,_format:json }

#acme_es_battle_admin_check_usergame:
#    path:     /francis/usergame
#    defaults: { _controller: AcmeEsBattleBundle:Admin:checkUserGame }
#
#acme_es_battle_admin_remove_old_usergame:
#    path:     /francis/remove
#    defaults: { _controller: AcmeEsBattleBundle:Admin:removeOldUserGame }
#
#acme_es_battle_admin_delete_old_usergame:
#    path:     /francis/delete
#    defaults: { _controller: AcmeEsBattleBundle:Admin:deleteOldUserGame }

#acme_es_battle_admin_copy_ps4:
#    path:     /francis/copy/{url}
#    defaults: { _controller: AcmeEsBattleBundle:Admin:copyJeuxVideo }

acme_es_battle_admin_upload:
    path:     /admin/upload
    defaults: { _controller: AcmeEsBattleBundle:Admin:upload }

acme_es_battle_admin_biblio:
    path:     /admin/biblio
    defaults: { _controller: AcmeEsBattleBundle:Admin:bibliotheque }

acme_es_battle_admin_topic:
    path:     /admin/topic/{id}
    defaults: { _controller: AcmeEsBattleBundle:Admin:topic }

acme_es_battle_admin_partenaire:
    path:     /admin/partenaire
    defaults: { _controller: AcmeEsBattleBundle:Admin:partenaire }

acme_es_battle_admin_partenaire_add:
    path:     /admin/partenaire/add/{id}
    defaults: { _controller: AcmeEsBattleBundle:Admin:addPartenaire }

acme_es_battle_admin_video:
    path:     /admin/video
    defaults: { _controller: AcmeEsBattleBundle:Admin:video }

acme_es_battle_admin_video_add:
    path:     /admin/video/add/{id}
    defaults: { _controller: AcmeEsBattleBundle:Admin:addVideo }

acme_es_battle_admin_news_add:
    path:     /admin/news/add/{id}
    defaults: { _controller: AcmeEsBattleBundle:Admin:addNews }

acme_es_battle_admin_redaction:
    path:     /admin/redaction
    defaults: { _controller: AcmeEsBattleBundle:Admin:redaction }


acme_es_battle_admin_login:
    path:     /admin/login
    defaults: { _controller: AcmeEsBattleBundle:Admin:login }


acme_es_battle_forum_topic_get_all:
    path:     /forum
    defaults: { _controller: AcmeEsBattleBundle:Forum:getAllTopic }

acme_es_battle_news_get_all:
    path:     /news.{_format}
    defaults: { _controller: AcmeEsBattleBundle:Forum:getNews,_format: json }

acme_es_battle_forum_topic_get_one:
    path:     /forum/topic/get/{id}/{page}/{nbResult}.{_format}
    defaults: { _controller: AcmeEsBattleBundle:Forum:getTopic,_format: json }

acme_es_battle_forum_topic_create:
    path:     /forum/topic/create/{username}/{token}
    defaults: { _controller: AcmeEsBattleBundle:Forum:createTopic }

acme_es_battle_forum_topic_message_create:
    path:     /forum/topic/message/{topicId}/{page}/{nbResult}/{username}/{token}
    defaults: { _controller: AcmeEsBattleBundle:Forum:createMessage }

acme_es_battle_forum_topic_message_update:
    path:     /forum/topic/message/update/{messageId}/{page}/{nbResult}/{username}/{token}
    defaults: { _controller: AcmeEsBattleBundle:Forum:updateMessage }

acme_es_battle_forum_topic_message_delete:
    path:     /forum/topic/message/delete/{messageId}/{page}/{nbResult}/{username}/{token}
    defaults: { _controller: AcmeEsBattleBundle:Forum:deleteMessage }

acme_es_battle_stats:
    path:     /stats
    defaults: { _controller: AcmeEsBattleBundle:Stats:index }

acme_es_battle_partenaire:
    path:     /partenaire
    defaults: { _controller: AcmeEsBattleBundle:Partenaire:index }

acme_es_battle_partenaire_get_one:
    path:     /partenaire/{id}
    defaults: { _controller: AcmeEsBattleBundle:Partenaire:get }

acme_es_battle_avis_get:
    path:     /avis/{id}.{_format}
    defaults: { _controller: AcmeEsBattleBundle:Avis:get,_format:json }
    methods:  [GET]

acme_es_battle_avis_add:
    path:     /avis/{id}
    defaults: { _controller: AcmeEsBattleBundle:Avis:post,_format:json }
    methods:  [POST]

acme_es_battle_avis_options:
    path:     /avis/{id}.{_format}
    defaults: { _controller: AcmeEsBattleBundle:Avis:options,_format:json }
    methods:  [OPTIONS]