acme_es_battle_homepage:
    path:     /hello/{name}
    defaults: { _controller: AcmeEsBattleBundle:Default:index }

acme_es_battle_login:
    path:     /login/{username}/{password}
    defaults: { _controller: AcmeEsBattleBundle:Login:index }

acme_es_battle_register:
    path:     /register/{email}/{password}/{username}
    defaults: { _controller: AcmeEsBattleBundle:Login:register }

acme_es_battle_rdv:
    path:     /rdv/
    defaults: { _controller: AcmeEsBattleBundle:Rdv:index }

acme_es_battle_rdv_create:
    path:     /rdv/add/{plateform}/{game}/{tags}/{description}/{start}/{duree}/{nbParticipant}/{username}/{token}
    defaults: { _controller: AcmeEsBattleBundle:Rdv:create }

acme_es_battle_rdv_get:
    path:     /rdv/get/{rdvId}
    defaults: { _controller: AcmeEsBattleBundle:Rdv:getRdvById }

acme_es_battle_rdv_join:
    path:     /rdv/join/{rdvId}/{username}/{apikey}
    defaults: { _controller: AcmeEsBattleBundle:Rdv:joinRdv }

acme_es_battle_rdv_accept_user:
    path:     /rdv/accept_user/{userId}/{rdvId}/{username}/{apikey}
    defaults: { _controller: AcmeEsBattleBundle:Rdv:acceptUser }

acme_es_battle_rdv_kick_user:
    path:     /rdv/kick_user/{userId}/{rdvId}/{username}/{apikey}
    defaults: { _controller: AcmeEsBattleBundle:Rdv:kickUser }

acme_es_battle_rdv_form_info:
    path:     /rdv/form_info
    defaults: { _controller: AcmeEsBattleBundle:Rdv:getFormInfo }

acme_es_battle_forget_password:
    path:     /forget_password/{email}
    defaults: { _controller: AcmeEsBattleBundle:Login:forgetPassword }
