acme_es_battle_homepage:
    path:     /hello/{name}
    defaults: { _controller: AcmeEsBattleBundle:Default:index }

acme_es_battle_login:
    path:     /loginold/{login}/{password}
    defaults: { _controller: AcmeEsBattleBundle:Login:index }

