acme_es_battle_homepage:
    path:     /hello/{name}
    defaults: { _controller: AcmeEsBattleBundle:Default:index }

acme_es_battle_login:
    path:     /login
    defaults: { _controller: AcmeEsBattleBundle:Login:index }

acme_es_battle_register:
    path:     /register/{email}/{password}/{username}
    defaults: { _controller: AcmeEsBattleBundle:Login:register }

acme_es_battle_rdv:
    path:     /rdv/
    defaults: { _controller: AcmeEsBattleBundle:Rdv:index }

acme_es_battle_rdv_create:
    path:     /rdv/add/{name}/{description}/{start}/{end}/{nbParticipant}
    defaults: { _controller: AcmeEsBattleBundle:Rdv:create }