parameters:
#    acme_es_battle.example.class: Acme\EsBattleBundle\Example

services:
#    acme_es_battle.example:
#        class: %acme_es_battle.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
