parameters:
    acme_es_battle.example.class: Acme\EsBattleBundle\Bungie
    acme_es_battle.jeuxvideo.class: Acme\EsBattleBundle\JeuxVideo

services:
    acme_es_battle.bungie:
        arguments: ["%bungie%","%destinyGameId%",@doctrine]
        class: "%acme_es_battle.example.class%"
    acme_es_battle.jeuxvideo:
            arguments: []
            class: "%acme_es_battle.jeuxvideo.class%"
#    acme_es_battle.example:
#        class: %acme_es_battle.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
