parameters:
    acme_es_battle.example.class: Acme\EsBattleBundle\Bungie

services:
    acme_es_battle.bungie:
        arguments: ["%bungie%","%destinyGameId%",@doctrine]
        class: "%acme_es_battle.example.class%"
#    acme_es_battle.example:
#        class: %acme_es_battle.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
